In [44]:
import numpy as np 
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, SimpleRNN, GRU
from sklearn.model_selection import train_test_split 
from sklearn.model_selection import train_test_split


In [ ]:
corpus = [
    "I love this movie, it was fantastic!",
    "Absolutely terrible, I hated every second.",
    "Best experience ever, really enjoyed it.",
    "It was okay, not the best but fine.",
    "Horrible acting, worst film of the year.",
    "Brilliant direction and acting!",
    "I would not recommend this to anyone.",
    "This film was a masterpiece.",
    "Very boring and too long.",
    "Amazing movie, I want to watch it again.",
    "Outstanding performances from the entire cast.",
    "Complete waste of time and money.",
    "Incredible cinematography and storytelling.",
    "The plot was confusing and poorly executed.",
    "One of the best films I've seen this year.",
    "Disappointing sequel that ruins the original.",
    "Beautifully crafted with excellent music.",
    "Predictable storyline with weak character development.",
    "Absolutely loved every minute of it.",
    "Terrible special effects and poor acting.",
    "A true work of art that moved me to tears.",
    "Boring dialogue and slow pacing throughout.",
    "Exceeded all my expectations, simply wonderful.",
    "Worst movie I've ever watched in my life.",
    "Perfect blend of action and emotion.",
    "Completely overrated and underwhelming.",
    "Stunning visuals and compelling narrative.",
    "Poorly written script with amateur directing.",
    "This movie changed my perspective on life.",
    "Absolute garbage, couldn't finish watching.",
    "Remarkable acting and beautiful soundtrack.",
    "Dull and repetitive with no substance.",
    "A cinematic gem that deserves recognition.",
    "Lacks originality and feels like a copycat.",
    "Thrilling from start to finish, loved it.",
    "Painfully long and incredibly boring.",
    "Masterful direction with powerful performances.",
    "Cheesy dialogue and unrealistic plot.",
    "One of my all-time favorite movies now.",
    "Mediocre at best, wouldn't watch again.",
    "Brilliant storytelling with great character arcs.",
    "Confusing mess that makes no sense.",
    "Emotionally engaging and visually stunning.",
    "Terrible editing and poor sound quality.",
    "A must-watch film that everyone should see.",
    "Overhyped movie that fails to deliver.",
    "Incredible action sequences and great humor.",
    "Annoying characters and ridiculous storyline.",
    "Perfectly executed with attention to detail.",
    "Boring and forgettable, nothing special.",
    "Amazing chemistry between the lead actors.",
    "Awkward performances and cringe-worthy moments.",
    "Thought-provoking film with deep meaning.",
    "Shallow plot with no character development.",
    "Excellent pacing and wonderful cinematography.",
    "Too long and drags in the middle.",
    "Captivating story that keeps you engaged.",
    "Predictable ending that ruins the experience.",
    "Outstanding direction and flawless execution.",
    "Poor acting and unconvincing dialogue.",
    "A beautiful film that touches your heart.",
    "Disappointing waste of talented actors.",
    "Innovative and fresh take on the genre.",
    "Clichéd and unoriginal storytelling.",
    "Phenomenal movie with incredible depth.",
    "Lacks focus and coherent narrative structure.",
    "Superb acting and brilliant writing.",
    "Terrible pacing and boring scenes.",
    "An absolute delight to watch.",
    "Worst sequel ever made, avoid at all costs.",
    "Perfectly balanced drama and comedy.",
    "Annoying soundtrack and poor editing.",
    "This movie deserves all the awards.",
    "Complete failure in every aspect.",
    "Engaging plot with unexpected twists.",
    "Predictable and formulaic approach.",
    "Wonderful performances by all actors.",
    "Terrible casting choices throughout.",
    "A masterpiece of modern cinema.",
    "Boring and lacks any entertainment value.",
    "Incredible journey that left me speechless.",
    "Poorly executed with many plot holes.",
    "Best movie of the decade, hands down.",
    "Absolute disaster, couldn't be worse.",
    "Beautiful storytelling with great music.",
    "Dreadful acting and weak storyline.",
    "Amazing special effects and solid plot.",
    "Confusing narrative that goes nowhere.",
    "Perfect movie for the whole family.",
    "Inappropriate content and poor taste.",
    "Brilliant performances and great direction.",
    "Lacks substance and feels empty.",
    "Emotionally powerful and well-crafted.",
    "Boring characters and slow development.",
    "Outstanding film that exceeded expectations.",
    "Disappointing adaptation of great source material.",
    "Incredible cinematography and sound design.",
    "Poor production values and bad writing.",
    "A true cinematic achievement.",
    "Overly long and self-indulgent.",
    "Fantastic movie that I'll watch again.",
    "Terrible experience from beginning to end.",
    "Compelling story with great character work.",
    "Shallow and lacks any real depth.",
    "Amazing direction and stellar cast.",
    "Poorly structured and confusing plot.",
    "One of the most beautiful films ever made.",
    "Completely forgettable and unremarkable.",
    "Incredible acting and emotional depth.",
    "Terrible dialogue and wooden performances.",
    "A movie that stays with you long after.",
    "Boring and predictable throughout.",
    "Perfect execution of a great concept.",
    "Failed attempt at being profound.",
    "Wonderful blend of humor and drama.",
    "Annoying characters and bad pacing.",
    "Absolutely stunning visual masterpiece.",
    "Poor special effects and cheap production.",
    "Great movie that deserves more recognition.",
    "Overhyped and ultimately disappointing.",
    "Brilliant storytelling and character development.",
    "Weak plot and unconvincing acting.",
    "An unforgettable cinematic experience.",
    "Forgettable movie with nothing new to offer.",
    "Excellent film with powerful message.",
    "Pointless story with no clear direction.",
    "Amazing performances from the entire cast.",
    "Terrible acting and poor directing.",
    "A work of art that inspires and entertains.",
    "Complete waste of time and resources.",
    "Incredible movie that touched my soul.",
    "Boring and lacks any emotional connection.",
    "Perfect balance of action and story.",
    "All action, no substance or depth.",
    "Outstanding film that deserves praise.",
    "Disappointing effort from talented director.",
    "Beautiful cinematography and great acting.",
    "Poor camera work and bad sound.",
    "A movie that redefines the genre.",
    "Generic and brings nothing new.",
    "Absolutely loved the character development.",
    "Flat characters with no personality.",
    "Incredible journey with perfect ending.",
    "Anticlimactic ending ruins the whole movie.",
    "This film is pure entertainment gold.",
    "Boring and feels like a chore to watch.",
    "Amazing soundtrack and visual effects.",
    "Poor music choices and bad editing.",
    "A true masterpiece of filmmaking.",
    "Amateur work that lacks professionalism.",
    "Fantastic movie that everyone should see.",
    "Terrible movie that nobody should watch.",
    "Brilliant direction and exceptional acting.",
    "Poor direction and mediocre performances.",
    "One of the best films of all time.",
    "One of the worst films ever made.",
    "Incredible story that captivates throughout.",
    "Dull story that fails to engage.",
    "Perfect movie with no flaws whatsoever.",
    "Flawed movie with many problems.",
    "Amazing film that exceeded all expectations.",
    "Disappointing film that fell short.",
    "Wonderful experience that I'll never forget.",
    "Forgettable experience I regret watching.",
    "Absolutely brilliant and innovative.",
    "Unoriginal and completely derivative.",
    "A movie that deserves multiple viewings.",
    "A movie I never want to see again.",
    "Outstanding performances and great story.",
    "Poor performances and weak story.",
    "Incredible film that moved me deeply.",
    "Shallow film that left me cold.",
    "Perfect casting and excellent direction.",
    "Miscast actors and poor direction.",
    "Amazing movie that I highly recommend.",
    "Terrible movie that I cannot recommend.",
    "Beautiful film with profound meaning.",
    "Meaningless film with no substance.",
    "Excellent pacing and wonderful acting.",
    "Poor pacing and terrible acting.",
    "A cinematic treasure that must be seen.",
    "A cinematic disaster to be avoided.",
    "Fantastic storytelling and great visuals.",
    "Poor storytelling and bad visuals.",
    "This movie is absolutely phenomenal.",
    "This movie is absolutely awful.",
    "Brilliant script and outstanding cast.",
    "Terrible script and awful cast.",
    "A film that will be remembered forever.",
    "A film that should be forgotten immediately.",
    "Exceptional quality in every aspect.",
    "Poor quality in every aspect.",
    "Magnificent directiofkfmnr kemffn and superb acting.",
    "Terrible direction and horrible acting.",
    "A true classic that stands the test of time.",
    "A disaster that fails on every level.",
    "Incredible depth and beautiful cinematography.",
    "Lacks depth and ugly cinematography.",
    "Perfect storytelling and amazing performances.",
    "Awful storytelling and terrible performances.",
    "A movie that inspires and uplifts.",
    "A movie that depresses and disappoints.",
    "Outstanding film with incredible visuals.",
    "Mediocre film with poor visuals.",
    "Brilliant execution of a fantastic concept.",
    "Poor execution of a weak concept.",
    "Amazing character development and plot.",
    "Weak character development and plot.",
    "A masterful work of cinematic art.",
    "A poor excuse for entertainment.",
    "Excellent dialogue and great chemistry.",
    "Poor dialogue and no chemistry.",
    "Stunning visuals and powerful story.",
    "Ugly visuals and weak story.",
    "Perfect blend of entertainment and art.",
    "Failed attempt at both entertainment and art.",
    "A movie that deserves critical acclaim.",
    "A movie that deserves to be forgotten.",
    "Incredible performances by everyone involved.",
    "Terrible performances by everyone involved.",
    "Beautiful music and exceptional direction.",
    "Awful music and poor direction.",
    "A film that touches the heart and mind.",
    "A film that offends the heart and mind.",
    "Outstanding achievement in filmmaking.",
    "Complete failure in filmmaking.",
    "Wonderful story with great execution.",
    "Terrible story with poor execution.",
    "A movie that exceeds all expectations.",
    "A movie that falls short of all expectations.",
    "Brilliant cinematography and perfect pacing.",
    "Poor cinematography and terrible pacing.",
    "An emotional masterpiece that moves you.",
    "An emotional disaster that annoys you.",
    "Incredible attention to detail throughout.",
    "Careless and sloppy throughout.",
    "A film that showcases true talent.",
    "A film that wastes true talent.",
    "Perfect combination of style and substance.",
    "Poor combination of style and substance.",
    "Amazing movie that deserves recognition.",
    "Terrible movie that deserves criticism.",
    "Excellent film with memorable characters.",
    "Poor film with forgettable characters.",
    "A true work of genius and creativity.",
    "A poor display of lack of creativity.",
    "Outstanding movie with perfect casting.",
    "Disappointing movie with poor casting.",
    "Brilliant film that sets new standards.",
    "Terrible film that lowers standards.",
    "A movie that celebrates the art of cinema.",
    "A movie that destroys the art of cinema.",
    "Incredible journey with satisfying conclusion.",
    "Boring journey with unsatisfying conclusion.",
    "Perfect example of excellent filmmaking.",
    "Perfect example of terrible filmmaking.",
    "Amazing story that captivates from start.",
    "Boring story that loses you from start.",
    "Outstanding direction and stellar performances.",
    "Poor direction and weak performances.",
    "A film that will inspire future generations.",
    "A film that will disappoint future generations.",
    "Incredible movie that deserves multiple awards.",
    "Terrible movie that deserves no recognition.",
    "Beautiful cinematography and moving story.",
    "Ugly cinematography and boring story.",
    "Perfect balance of all cinematic elements.",
    "Poor balance of all cinematic elements.",
    "A masterpiece that defines great cinema.",
    "A disaster that defines bad cinema.",
    "Amazing film with unforgettable moments.",
    "Forgettable film with no memorable moments.",
    "Brilliant work that showcases pure talent.",
    "Poor work that shows lack of talent.",
    "Incredible movie that leaves lasting impact.",
    "Terrible movie that leaves no impact.",
    "Outstanding film that deserves preservation.",
    "Disappointing film that deserves disposal."
]

labels = [
    1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0
]

In [45]:
tokenizer = Tokenizer(num_words=1000, oov_token="<OOV>")
tokenizer.fit_on_texts(corpus)

In [46]:
tokenizer

In [47]:
sequences = tokenizer.texts_to_sequences(corpus)
tokens

NameError: name 'tokens' is not defined

In [48]:
sequences

[[22,
  23,
  6,
  13,
  24,
  25,
  26,
  2,
  27,
  28,
  10,
  14,
  29,
  15,
  16,
  3,
  30,
  7,
  31,
  32,
  16,
  33,
  34,
  35,
  11,
  17,
  36,
  37,
  38,
  39,
  40,
  3,
  41,
  18,
  42,
  6,
  43,
  8,
  44,
  45,
  46,
  47,
  48,
  9,
  49,
  11,
  50,
  19,
  51,
  52,
  17,
  53,
  54,
  18,
  55,
  7,
  56,
  2,
  57,
  58,
  6,
  59,
  60,
  61,
  62],
 [8,
  63,
  7,
  10,
  64,
  65,
  66,
  8,
  2,
  67,
  68,
  69,
  70,
  71,
  72,
  20,
  10,
  2,
  73,
  74,
  19,
  75,
  76,
  77,
  14,
  15,
  78,
  79,
  3,
  20,
  7,
  80,
  6,
  81,
  82,
  9,
  3,
  83,
  13,
  84,
  85,
  86,
  87,
  8,
  3,
  88],
 [89, 12, 4, 2, 90, 9, 91, 12],
 [92, 93, 94, 4, 2, 95, 9, 5],
 [5, 4, 3, 96],
 [97, 98, 21, 5],
 [11, 99, 5, 100],
 [12, 101, 102, 4, 103],
 [21, 5, 4, 104]]

In [49]:
maxlen = 10
padded_sequences = pad_sequences(sequences, maxlen=maxlen, padding='post', truncating='post')

In [50]:
padded_sequences

array([[ 22,  23,   6,  13,  24,  25,  26,   2,  27,  28],
       [  8,  63,   7,  10,  64,  65,  66,   8,   2,  67],
       [ 89,  12,   4,   2,  90,   9,  91,  12,   0,   0],
       [ 92,  93,  94,   4,   2,  95,   9,   5,   0,   0],
       [  5,   4,   3,  96,   0,   0,   0,   0,   0,   0],
       [ 97,  98,  21,   5,   0,   0,   0,   0,   0,   0],
       [ 11,  99,   5, 100,   0,   0,   0,   0,   0,   0],
       [ 12, 101, 102,   4, 103,   0,   0,   0,   0,   0],
       [ 21,   5,   4, 104,   0,   0,   0,   0,   0,   0]])

In [51]:
x_train, x_test, y_train, y_test = train_test_split(padded_sequences, labels[:len(padded_sequences)], test_size=0.2, random_state=42)

In [52]:
x_train, x_test, y_train, y_test

(array([[ 97,  98,  21,   5,   0,   0,   0,   0,   0,   0],
        [ 22,  23,   6,  13,  24,  25,  26,   2,  27,  28],
        [ 21,   5,   4, 104,   0,   0,   0,   0,   0,   0],
        [ 89,  12,   4,   2,  90,   9,  91,  12,   0,   0],
        [  5,   4,   3,  96,   0,   0,   0,   0,   0,   0],
        [ 92,  93,  94,   4,   2,  95,   9,   5,   0,   0],
        [ 11,  99,   5, 100,   0,   0,   0,   0,   0,   0]]),
 array([[ 12, 101, 102,   4, 103,   0,   0,   0,   0,   0],
        [  8,  63,   7,  10,  64,  65,  66,   8,   2,  67]]),
 [1, 1, 0, 1, 0, 1, 0],
 [1, 0])

In [53]:
rnn_model = Sequential([
    Embedding(input_dim=1000, output_dim=32, input_length=maxlen),
    SimpleRNN(64, return_sequences=True),
    Dropout(0.5),
    SimpleRNN(32),
    Dense(1, activation='sigmoid')
])  

c:\Users\Deepu\anaconda3\envs\nlp\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [54]:
rnn_model_lstm = Sequential([
    Embedding(input_dim=1000, output_dim=32, input_length=maxlen),
    LSTM(64, return_sequences=True),
    Dropout(0.5),  
    LSTM(32),
    Dense(1, activation='sigmoid')
])

In [57]:
rnn_model_gru = Sequential([
    Embedding(input_dim=1000, output_dim=32, input_length=maxlen),
    GRU(64, return_sequences=True),
    Dropout(0.5),
    GRU(32),
    Dense(1, activation='sigmoid')
])


In [58]:
rnn_model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
print("now i will start the training")
rnn_model.fit(np.array(x_train),np.array(y_train),epochs=100 , verbose=2)

now i will start the training
Epoch 1/100
1/1 - 3s - 3s/step - accuracy: 0.5714 - loss: 0.7179
Epoch 2/100
1/1 - 0s - 39ms/step - accuracy: 0.8571 - loss: 0.5754
Epoch 3/100
1/1 - 0s - 41ms/step - accuracy: 0.5714 - loss: 0.6240
Epoch 4/100
1/1 - 0s - 39ms/step - accuracy: 0.8571 - loss: 0.5659
Epoch 5/100
1/1 - 0s - 73ms/step - accuracy: 0.8571 - loss: 0.5315
Epoch 6/100
1/1 - 0s - 38ms/step - accuracy: 0.7143 - loss: 0.5639
Epoch 7/100
1/1 - 0s - 40ms/step - accuracy: 1.0000 - loss: 0.4548
Epoch 8/100
1/1 - 0s - 41ms/step - accuracy: 1.0000 - loss: 0.3830
Epoch 9/100
1/1 - 0s - 43ms/step - accuracy: 1.0000 - loss: 0.3265
Epoch 10/100
1/1 - 0s - 39ms/step - accuracy: 1.0000 - loss: 0.3502
Epoch 11/100
1/1 - 0s - 42ms/step - accuracy: 1.0000 - loss: 0.2614
Epoch 12/100
1/1 - 0s - 40ms/step - accuracy: 1.0000 - loss: 0.2195
Epoch 13/100
1/1 - 0s - 44ms/step - accuracy: 1.0000 - loss: 0.1715
Epoch 14/100
1/1 - 0s - 57ms/step - accuracy: 1.0000 - loss: 0.1835
Epoch 15/100
1/1 - 0s - 65ms/

In [59]:
rnn_model.evaluate(np.array(x_test),np.array(y_test),verbose=34)

[0.37589603662490845, 1.0]

In [66]:
sample_data = ["poor story with bad performance"]
sample_token = tokenizer.texts_to_sequences(sample_data)

In [67]:
sample_pad_data = pad_sequences(sample_token , maxlen = 15 , padding='post')

In [68]:
sample_pad_data

array([[ 1,  1, 40,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [71]:
rnn_model_gru.predict(sample_pad_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step


array([[0.50925004]], dtype=float32)

In [72]:
rnn_model_lstm.predict(sample_pad_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([[0.50093925]], dtype=float32)

In [73]:
rnn_model.predict(sample_pad_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[0.13113078]], dtype=float32)